#!/bin/sh
#
# termgpt-platform.sh - Platform-specific command mappings
#
# This file is sourced by termgpt to provide platform-appropriate commands
# It's generated by setup.sh based on detected OS and available tools

# Default platform (will be overridden by setup.sh)
TERMGPT_PLATFORM="${TERMGPT_PLATFORM:-unknown}"

# Platform-specific clipboard commands
get_clipboard_cmd() {
  case "$TERMGPT_PLATFORM" in
    macos)
      echo "pbcopy"
      ;;
    linux)
      if command -v xclip >/dev/null 2>&1; then
        echo "xclip -selection clipboard"
      elif command -v xsel >/dev/null 2>&1; then
        echo "xsel --clipboard --input"
      elif command -v wl-copy >/dev/null 2>&1; then
        echo "wl-copy"
      fi
      ;;
  esac
}

# Platform-specific open URL commands
get_open_url_cmd() {
  case "$TERMGPT_PLATFORM" in
    macos)
      echo "open"
      ;;
    linux)
      if command -v xdg-open >/dev/null 2>&1; then
        echo "xdg-open"
      elif command -v gnome-open >/dev/null 2>&1; then
        echo "gnome-open"
      elif command -v kde-open >/dev/null 2>&1; then
        echo "kde-open"
      fi
      ;;
  esac
}

# Platform-specific package manager (simplified)
get_package_manager() {
  case "$TERMGPT_PLATFORM" in
    macos)
      command -v brew >/dev/null 2>&1 && echo "brew"
      ;;
    linux)
      if command -v apt-get >/dev/null 2>&1; then
        echo "apt"
      elif command -v yum >/dev/null 2>&1; then
        echo "yum"
      elif command -v pacman >/dev/null 2>&1; then
        echo "pacman"
      fi
      ;;
  esac
}

